# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7071a0f1eb7eff847e610ac62f0d221303a1cffd11b708ba622b0a63390f519baa894e0e226f280a09e62a5185f5f764ec80b9f6020e12597e11b836a45cda2e
  fb_id: 1688577457876369
  fb_secret: 13646da17ac543b3fa3bdf93bd143f33

test:
  secret_key_base: ff44848f4ad61a46e2edfb27b2477e5671dbc8091e46916c8f12853917092718cc23bdf2c672d8865be9e95d3bb8f2e681fbb8786adcafe347ded26ce76302bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
